package rentalps_tim3;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalTime; // Import the LocalDateTime class
import java.time.format.DateTimeFormatter; // Import the DateTimeFormatter class
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Syifa Putri Andini
 */
public class tampilanRentalPS extends javax.swing.JFrame {
    LocalTime jamMasuk = LocalTime.now();
    DateTimeFormatter FOMATTER = DateTimeFormatter.ofPattern("HH:mm");
    String localTimeString = FOMATTER.format( LocalTime.now() );
    
    /**
     * Creates new form tampilanRentalPS
     */
    public tampilanRentalPS() {
        initComponents();
    }
    String username, name;
    public tampilanRentalPS(String username, String name){
         initComponents();
         this.username = username;
         this.name = name;
         nama.setText(name);
         Username.setText(username);
         lbJamLogin.setText(localTimeString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbJenisPs = new javax.swing.JComboBox<>();
        cbMeja = new javax.swing.JComboBox<>();
        txtJamMasuk = new javax.swing.JTextField();
        txtJamKeluar = new javax.swing.JTextField();
        txtTagihan = new javax.swing.JTextField();
        sDurasi = new javax.swing.JSpinner();
        btnProses = new javax.swing.JButton();
        txtHarga = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNoTrans = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnLaporan = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabel20 = new javax.swing.JLabel();
        lbPendapatan = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbKunjungan = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbTagihanTerbesar = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        lbTagihanTerendah = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbWaktuTerlama = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbRataWaktu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtIdUser = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btn_cari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btn_refresh = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_IdUser = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbJamLogin = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RENTAL PS TEAM 3");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Jenis PS");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Durasi");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Jam Masuk");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("Meja ");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setLabelFor(txtJamKeluar);
        jLabel6.setText("Jam Keluar");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setText("Tagihan");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setText("Harga per Jam");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setText("Jam");

        cbJenisPs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbJenisPs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis PS", "PlayStation 2", "PlayStation 3", "PlayStation 4", "PlayStation 5" }));
        cbJenisPs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbJenisPsMouseClicked(evt);
            }
        });
        cbJenisPs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisPsActionPerformed(evt);
            }
        });

        cbMeja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbMeja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih No. Meja", "Meja 1", "Meja 2", "Meja 3", "Meja 4", "Meja 5", "Meja 6", "Meja 7", "Meja 8" }));
        cbMeja.setEnabled(false);
        cbMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMejaActionPerformed(evt);
            }
        });

        txtJamMasuk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtJamMasuk.setText(localTimeString);
        txtJamMasuk.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtJamMasukComponentShown(evt);
            }
        });
        txtJamMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJamMasukActionPerformed(evt);
            }
        });

        txtJamKeluar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTagihan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        sDurasi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sDurasi.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        btnProses.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnProses.setText("PROSES");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        txtHarga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHarga.setEnabled(false);
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel9))
                            .addComponent(cbJenisPs, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtJamKeluar)
                                    .addComponent(txtTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtJamKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(cbJenisPs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addComponent(cbMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Kasir", jPanel1);

        txtNoTrans.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel12.setText("No. Transaksi");

        btnCari.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRefresh.setText("REFRESH TABLE");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtNoTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCari)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btnCari))
                .addGap(20, 20, 20)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Riwayat Transaksi", jPanel2);

        btnLaporan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnLaporan.setText("LIHAT LAPORAN");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Berikut ini adalah laporan operasional Rental PS setiap harinya");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("TOTAL PENDAPATAN");

        lbPendapatan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbPendapatan.setText("Rp. ");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("JUMLAH KUNJUNGAN");

        lbKunjungan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbKunjungan.setText("XXX");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("TAGIHAN TERBESAR");

        lbTagihanTerbesar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTagihanTerbesar.setText("Rp. ");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Jenis PS yang sering dimainkan");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("TAGIHAN TERENDAH");

        lbTagihanTerendah.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTagihanTerendah.setText("Rp. ");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("WAKTU TERLAMA BERMAIN PS");

        lbWaktuTerlama.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbWaktuTerlama.setText("XX Jam");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("RATA RATA LAMA BERMAIN PS");

        lbRataWaktu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbRataWaktu.setText("XX Jam");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(30, 30, 30)
                        .addComponent(btnLaporan)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(lbPendapatan)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTagihanTerbesar)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22)
                            .addComponent(lbKunjungan))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTagihanTerendah)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27)
                            .addComponent(lbWaktuTerlama)
                            .addComponent(jLabel29)
                            .addComponent(lbRataWaktu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(63, 63, 63))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(btnLaporan))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel25))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPendapatan)
                            .addComponent(lbTagihanTerendah))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel27))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbKunjungan)
                            .addComponent(lbWaktuTerlama))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel29))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTagihanTerbesar)
                            .addComponent(lbRataWaktu)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Laporan Operasional", jPanel3);

        txtIdUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setText("ID User");

        btn_cari.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_cari.setText("CARI");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btn_refresh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_refresh.setText("REFRESH TABLE");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cari)
                .addGap(197, 197, 197)
                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(btn_cari))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Informasi Akun Admin", jPanel4);

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setText("ID User");

        txt_IdUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setText("Nama Pegawai");

        txt_nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setText("Username");

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setText("Password");

        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable4MousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("REFRESH TABLE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_username)
                            .addComponent(txt_nama)
                            .addComponent(txt_IdUser)
                            .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(47, 47, 47))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_IdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manajemen Akun Admin", jPanel5);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("Selamat Datang, ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Username :");

        Username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Username.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UsernameComponentShown(evt);
            }
        });

        nama.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 51, 0));
        nama.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                namaComponentShown(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Jam Login :");

        lbJamLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbJamLogin.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lbJamLoginComponentShown(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnLogOut.setText("LOG OUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nama)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username)
                .addGap(182, 182, 182)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbJamLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Username)
                    .addComponent(jLabel13)
                    .addComponent(lbJamLogin)
                    .addComponent(btnLogOut))
                .addGap(11, 11, 11))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void cbJenisPsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbJenisPsMouseClicked
      
    
    }//GEN-LAST:event_cbJenisPsMouseClicked

    private void cbJenisPsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisPsActionPerformed
      int harga = 0;
      if (cbJenisPs.getSelectedItem() == "PlayStation 2" ){
           harga = 10000;
      }
      else if (cbJenisPs.getSelectedItem() == "PlayStation 3" ){
          harga = 12000;
      }
      else if (cbJenisPs.getSelectedItem() == "PlayStation 4" ){
          harga = 15000;
      }
      else if (cbJenisPs.getSelectedItem() == "PlayStation 5" ){
          harga = 20000;
      }
        txtHarga.setText(String.valueOf(harga));
        if(cbJenisPs.getSelectedItem() != "Pilih Jenis PS" ){
            cbMeja.setEnabled(true);
        }
    }//GEN-LAST:event_cbJenisPsActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        double tagihan;
        tagihan = Integer.parseInt(txtHarga.getText()) * (int)sDurasi.getValue();
        txtTagihan.setText(String.valueOf(tagihan));
        LocalTime jamKeluar = jamMasuk.plusHours((int)sDurasi.getValue()).plusMinutes(0);
        String jamKeluarString = FOMATTER.format(jamKeluar);
        txtJamKeluar.setText(jamKeluarString);
        
        // Proses mencatat transaksi ke database
        Koneksi conn = new Koneksi();
        String jenis_ps = String.valueOf(cbJenisPs.getSelectedItem());
        int durasi = Integer.parseInt(String.valueOf(sDurasi.getValue()));
        String no_meja = String.valueOf(cbMeja.getSelectedItem());
        
        String query =  "insert into transaksi (jenis_ps, durasi, no_meja, jam_masuk, jam_keluar, total_tagihan) values ('" 
                + jenis_ps + "', " + durasi + ", '" + no_meja + "', '" + localTimeString + "', '" + jamKeluarString + "', " + tagihan + ")";
        try{
            conn.getStatement().executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Transaksi berhasil dicatat! \nSelamat bermain!", "Information", JOptionPane.INFORMATION_MESSAGE);   
        }
        catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Yah! Transaksi gagal dicatat. \nMohon coba lagi nanti.");
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtJamMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJamMasukActionPerformed

    }//GEN-LAST:event_txtJamMasukActionPerformed

    private void txtJamMasukComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtJamMasukComponentShown
        txtJamMasuk.setText(localTimeString); 
    }//GEN-LAST:event_txtJamMasukComponentShown

    private void cbMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMejaActionPerformed
        
    }//GEN-LAST:event_cbMejaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        cbJenisPs.setSelectedItem("Pilih Jenis PS");
        cbMeja.setSelectedItem("Pilih No. Meja");
        txtHarga.setText("");
        txtJamMasuk.setText(localTimeString);
        txtJamKeluar.setText("");
        txtTagihan.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        Koneksi conn = new Koneksi();
        ResultSet data = null;
        int jumBaris = 0;
        int i = 0;
        String query = "SELECT * FROM transaksi";
        try{
            data = conn.getStatement().executeQuery(query);
            
            while(data.next()){
                jumBaris++;
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        
        String isi[][] = new String[jumBaris][7];
        
        try{
            data = conn.getStatement().executeQuery(query);
            
            while(data.next()){
                isi[i][0] = data.getString("no_transaksi");
                isi[i][1] = data.getString("jenis_ps");
                isi[i][2] = data.getString("durasi");
                isi[i][3] = data.getString("no_meja");
                isi[i][4] = data.getString("jam_masuk");
                isi[i][5] = data.getString("jam_keluar");
                isi[i][6] = data.getString("total_tagihan");
                i++;
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error lagi");
        }
        
        String namaKolom[] = {"No. Transaksi", "Jenis PS", "Durasi Main", "No. Meja", "Jam Masuk", "Jam Keluar", "Total Tagihan"};
        DefaultTableModel model = new DefaultTableModel(isi, namaKolom){};
        jTable1.setModel(model);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void namaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_namaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_namaComponentShown

    private void UsernameComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UsernameComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameComponentShown

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        Koneksi conn = new Koneksi();
        ResultSet data = null;
        int jumBaris = 0;
        int i = 0;
        String query = "SELECT * FROM transaksi where no_transaksi = " + txtNoTrans.getText();
        try{
            data = conn.getStatement().executeQuery(query);
            
            while(data.next()){
                jumBaris++;
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        
        String isi[][] = new String[jumBaris][7];
        
        try{
            data = conn.getStatement().executeQuery(query);
            
            while(data.next()){
                isi[i][0] = data.getString("no_transaksi");
                isi[i][1] = data.getString("jenis_ps");
                isi[i][2] = data.getString("durasi");
                isi[i][3] = data.getString("no_meja");
                isi[i][4] = data.getString("jam_masuk");
                isi[i][5] = data.getString("jam_keluar");
                isi[i][6] = data.getString("total_tagihan");
                i++;
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error lagi");
        }
        
        String namaKolom[] = {"No. Transaksi", "Jenis PS", "Durasi Main", "No. Meja", "Jam Masuk", "Jam Keluar", "Total Tagihan"};
        DefaultTableModel model = new DefaultTableModel(isi, namaKolom){};
        jTable1.setModel(model);
    }//GEN-LAST:event_btnCariActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        Koneksi conn = new Koneksi();
        ResultSet data = null;
        int jumBaris = 0;
        int i = 0;
        String query = "SELECT * FROM user";
        try{
            data = conn.getStatement().executeQuery(query);
            
            while(data.next()){
                jumBaris++;
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        
        String isi[][] = new String[jumBaris][4];
        
        try{
            data = conn.getStatement().executeQuery(query);
            
            while(data.next()){
                isi[i][0] = data.getString("id_user");
                isi[i][1] = data.getString("nama_pegawai");
                isi[i][2] = data.getString("username");
                isi[i][3] = data.getString("password");
                i++;
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error lagi");
        }
        
        String namaKolom[] = {"ID User", "Nama Pegawai", "Username", "Password"};
        DefaultTableModel model = new DefaultTableModel(isi, namaKolom){};
        jTable2.setModel(model);
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        Koneksi conn = new Koneksi();
        ResultSet data = null;
        int jumBaris = 0;
        int i = 0;
        String query = "SELECT * FROM user where id_user = " + txtIdUser.getText();
        
        try{
            data = conn.getStatement().executeQuery(query);
            
            while(data.next()){
                jumBaris++;
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        
        String isi[][] = new String[jumBaris][4];
        
        try{
            data = conn.getStatement().executeQuery(query);
            
            while(data.next()){
                isi[i][0] = data.getString("id_user");
                isi[i][1] = data.getString("nama_pegawai");
                isi[i][2] = data.getString("username");
                isi[i][3] = data.getString("password");
                i++;
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error lagi");
        }
        
        String namaKolom[] = {"ID User", "Nama Pegawai", "Username", "Password"};
        DefaultTableModel model = new DefaultTableModel(isi, namaKolom){};
        jTable2.setModel(model);
    }//GEN-LAST:event_btn_cariActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Koneksi conn = new Koneksi();
        ResultSet data = null;
        int jumBaris = 0;
        int i = 0;
        String query = "SELECT * FROM user";
        try{
            data = conn.getStatement().executeQuery(query);
            
            while(data.next()){
                jumBaris++;
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        
        String isi[][] = new String[jumBaris][4];
        
        try{
            data = conn.getStatement().executeQuery(query);
            
            while(data.next()){
                isi[i][0] = data.getString("id_user");
                isi[i][1] = data.getString("nama_pegawai");
                isi[i][2] = data.getString("username");
                isi[i][3] = data.getString("password");
                i++;
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error lagi");
        }
        
        String namaKolom[] = {"ID User", "Nama Pegawai", "Username", "Password"};
        DefaultTableModel model = new DefaultTableModel(isi, namaKolom){};
        jTable4.setModel(model);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // Deklarasi Variabel
        Koneksi conn = new Koneksi();
        ResultSet data = null;
        int jumBaris = 0;
        int i = 0;
        String query;
        
        // Laporan total pendapatan hari ini
        query = "select sum(total_tagihan) as pendapatan from transaksi";
        try{
            data = conn.getStatement().executeQuery(query);
            data.next();
            lbPendapatan.setText("Rp. " + data.getString("pendapatan"));
        }
        catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        
        // Laporan jumlah kunjungan hari ini
        query = "select count(no_transaksi) as jumlah_kunjungan from transaksi";
        try{
            data = conn.getStatement().executeQuery(query);
            data.next();
            lbKunjungan.setText(data.getString("jumlah_kunjungan") + " Pengunjung");
        }
        catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        
        // Laporan tagihan terbesar hari ini
        query = "select max(total_tagihan) as tagihan_terbesar from transaksi";
        try{
            data = conn.getStatement().executeQuery(query);
            data.next();
            lbTagihanTerbesar.setText("Rp. " + data.getString("tagihan_terbesar"));
        }
        catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        
        // Laporan tagihan terendah hari ini
        query = "select min(total_tagihan) as tagihan_terendah from transaksi";
        try{
            data = conn.getStatement().executeQuery(query);
            data.next();
            lbTagihanTerendah.setText("Rp. " + data.getString("tagihan_terendah"));
        }
        catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        
       // Laporan waktu terlama bermain hari ini
        query = "select max(durasi) as main_terlama from transaksi";
        try{
            data = conn.getStatement().executeQuery(query);
            data.next();
            lbWaktuTerlama.setText(data.getString("main_terlama") + " Jam");
        }
        catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        
        // Laporan rata rata waktu bermain hari ini
        query = "select avg(durasi) as rata_rata_bermain from transaksi";
        try{
            data = conn.getStatement().executeQuery(query);
            data.next();
            lbRataWaktu.setText(data.getString("rata_rata_bermain") + " Jam");
        }
        catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        // Laporan Jenis PS yang sering dimainkan
        query = "select jenis_ps, count(no_transaksi) as jumlah_pemain from transaksi group by jenis_ps order by jumlah_pemain desc";
        try{
            data = conn.getStatement().executeQuery(query);
            
            while(data.next()){
                jumBaris++;
            }
        }
        catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "ERROR");
        }
        
        String isi[][] = new String[jumBaris][2];
        
        try{
            data = conn.getStatement().executeQuery(query);
            
            while(data.next()){
                isi[i][0] = data.getString("jenis_ps");
                isi[i][1] = data.getString("jumlah_pemain");
                i++;
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error lagi");
        }
        
        String namaKolom[] = {"Jenis PS", "Jumlah Pemain"};
        DefaultTableModel model = new DefaultTableModel(isi, namaKolom){};
        jTable3.setModel(model);
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void lbJamLoginComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lbJamLoginComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lbJamLoginComponentShown

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        new tampilanLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void jTable4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MousePressed
        // TODO add your handling code here:
        String idUSer = (String) jTable4.getValueAt(jTable4.getSelectedRow() , 0);
        String namaPegawai = (String) jTable4.getValueAt(jTable4.getSelectedRow() , 1);
        String usn = (String) jTable4.getValueAt(jTable4.getSelectedRow() , 2);
        String pass = (String) jTable4.getValueAt(jTable4.getSelectedRow() , 3);
        
        // Menampilkan data akun pegawai dari database
        txt_IdUser.setText(idUSer);
        txt_nama.setText(namaPegawai);
        txt_username.setText(usn);
        txt_password.setText(pass);
    }//GEN-LAST:event_jTable4MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Koneksi conn = new Koneksi();
        
        String idUser = txt_IdUser.getText();
        String namaPegawai = txt_nama.getText();
        String usn = txt_username.getText();
        String pass = txt_password.getText();
        String query = "update user set nama_pegawai = '"+namaPegawai+"', username = '"+usn+"', password = '"+pass+"' where id_user= "+idUser;
        
        try{
            conn.getStatement().executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Yeay! Update data berhasil! \nSilakan refresh tabel Anda.");
        }

        catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Mohon maaf, update gagal \nMohon coba lagi nanti."); 
        }                               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Koneksi conn = new Koneksi();
        
        String idUser = txt_IdUser.getText();
        String query = "delete from user where id_user = "+idUser;
        
        try {
            int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus akun ini? \nAkun yang telah terhapus tidak dapat dikembalikan lagi.");
            
            if (konfirmasi == 0 ) {
                conn.getStatement().executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Akun telah berhasil dihapus!");
            }
        }
        catch (SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error SQL !");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilanRentalPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilanRentalPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilanRentalPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilanRentalPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilanRentalPS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JComboBox<String> cbJenisPs;
    private javax.swing.JComboBox<String> cbMeja;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lbJamLogin;
    private javax.swing.JLabel lbKunjungan;
    private javax.swing.JLabel lbPendapatan;
    private javax.swing.JLabel lbRataWaktu;
    private javax.swing.JLabel lbTagihanTerbesar;
    private javax.swing.JLabel lbTagihanTerendah;
    private javax.swing.JLabel lbWaktuTerlama;
    private javax.swing.JLabel nama;
    private javax.swing.JSpinner sDurasi;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdUser;
    private javax.swing.JTextField txtJamKeluar;
    private javax.swing.JTextField txtJamMasuk;
    private javax.swing.JTextField txtNoTrans;
    private javax.swing.JTextField txtTagihan;
    private javax.swing.JTextField txt_IdUser;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
